services:
  nginx:
    container_name: inception_nginx
    image: inception/nginx
    build: requirements/nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - inception_app_data:/app
    networks:
      - inception_net
    restart: always

  wordpress:
    container_name: inception_wordpress
    image: inception/wordpress
    build: requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - inception_app_data:/app
    env_file: .env
    networks:
      - inception_net
    restart: unless-stopped

  mariadb:
    container_name: inception_mariadb
    image: inception/mariadb
    build: requirements/mariadb
    volumes:
      - inception_db_data:/var/lib/mysql
    env_file: .env
    networks:
      - inception_net
    restart: unless-stopped

#bonus 
  adminer:
    container_name: inception_adminer
    image: inception/adminer
    build: requirements/bonus/adminer
    depends_on:
      - mariadb
    ports:
      - "8080:80" # Map port 8080 on the host to port 80 in the container
    networks:
      - inception_net

  ftpserver:
    container_name: inception_ftpserver
    image: inception/ftpserver
    build: requirements/bonus/ftpServer
    ports:
      - "21:21"
      - "40000-40005:40000-40005"
    volumes:
      - inception_app_data:/home/lagea/data/wordpress
    env_file: .env
    depends_on:
      - wordpress
    
  redis:
    container_name: inception_redis
    image: inception/redis
    build: requirements/bonus/redis
    volumes:
     - inception_app_data:/home/lagea/data/wordpress
    depends_on:
      - wordpress
    networks:
      - inception_net
    restart: always

  #static:
    #container_name: inception_static
    #image: inception/static
    #build: requirements/bonus/static
    #ports:
    #  - "80:80"
    #restart: always

  cadvisor:
    container_name: inception_cadvisor
    build: requirements/bonus/cadvisor
    image: 42_cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
        - monitoring-network
    command:
      - '-port=7000'
      - '-url_base_prefix=/cadvisor'
    restart: unless-stopped


networks:
  inception_net:
    driver: bridge

volumes:
  inception_app_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/lagea/data/wordpress'

  inception_db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/lagea/data/mariadb'