services:
  nginx:
    container_name: inception_nginx
    image: nginx
    build: requirements/nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - inception_app_data:/app
    networks:
      - inception_net
    restart: always

  wordpress:
    container_name: inception_wordpress
    image: wordpress
    build: requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - inception_app_data:/app
    env_file: .env
    networks:
      - inception_net
    restart: unless-stopped

  mariadb:
    container_name: inception_mariadb
    image: mariadb
    build: requirements/mariadb
    volumes:
      - inception_db_data:/var/lib/mysql
    env_file: .env
    networks:
      - inception_net
    restart: unless-stopped

#bonus 
  adminer:
    container_name: inception_adminer
    image: adminer
    build: requirements/bonus/adminer
    depends_on:
      - mariadb
    ports:
      - "8080:80" # Map port 8080 on the host to port 80 in the container
    networks:
      - inception_net

  ftpserver:
    container_name: inception_ftpserver
    image: tpserver
    build: requirements/bonus/ftpServer
    ports:
      - "21:21"
      - "40000-40005:40000-40005"
    volumes:
      - inception_app_data:/home/lagea/data/wordpress
    env_file: .env
    depends_on:
      - wordpress

  static:
    container_name: inception_static
    image: static
    build: requirements/bonus/static
    ports:
      - "80:80"
    restart: always

networks:
  inception_net:
    driver: bridge

volumes:
  inception_app_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/lagea/data/wordpress'

  inception_db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/lagea/data/mariadb'