# Use Debian as the base image
FROM debian:bullseye

# Set non-interactive mode for package installation
ENV DEBIAN_FRONTEND=noninteractive

# Update and install required packages
RUN apt-get update && apt-get install -y \
    vsftpd \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY ./tools/setup.sh /
RUN chmod +x /setup.sh

# Command to start vsftpd
CMD ["/setup.sh"]
