global:
  scrape_interval: 15s # How often to scrape targets by default

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nginx'
    static_configs:
      - targets: ['lagea.42.fr:443']
      
