FROM debian:bullseye

RUN apt-get update -y && apt-get upgrade -y \
        && apt-get install -y nginx

RUN echo "server {" > /etc/nginx/http.d/default.conf && \
        echo "root    /var/www;" >> /etc/nginx/http.d/default.conf && \
        echo "location / {" >> /etc/nginx/http.d/default.conf && \
        echo "    try_files \$uri /index.html;" >> /etc/nginx/http.d/default.conf && \
        echo "}}" >> /etc/nginx/http.d/default.conf
    
COPY requirements/bonus/static/website/* /var/www/

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]