FROM debian:bullseye

# Install necessary tools
RUN apt-get update -y && apt-get install -y \
    wget \
    tar \
    curl \
    ca-certificates && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set Grafana version
ENV GRAFANA_VERSION=10.1.0

# Download and extract Grafana
RUN wget https://dl.grafana.com/oss/release/grafana-${GRAFANA_VERSION}.linux-amd64.tar.gz && \
    tar -xvf grafana-${GRAFANA_VERSION}.linux-amd64.tar.gz && \
    mv grafana-${GRAFANA_VERSION} /grafana && \
    rm grafana-${GRAFANA_VERSION}.linux-amd64.tar.gz

# Expose Grafana web UI port
EXPOSE 3000

COPY provisioning /etc/grafana/provisioning

# Set working directory
WORKDIR /grafana

# Run Grafana
ENTRYPOINT ["/usr/sbin/grafana-server", "--homepath=/usr/share/grafana", "--config=/etc/grafana/grafana.ini", "--packaging=docker"]